"""Add search_type to CountryHistory model

Revision ID: 0f73504ba6bb
Revises: db34b1cc40db
Create Date: 2025-05-08 17:23:39.337342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f73504ba6bb'
down_revision = 'db34b1cc40db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('country_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('search_type', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('country_history', schema=None) as batch_op:
        batch_op.drop_column('search_type')

    # ### end Alembic commands ###
