"""rename query column to search_query

Revision ID: 704345399a21
Revises: e77344d00645
Create Date: 2025-05-13 12:09:37.754177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '704345399a21'
down_revision = 'e77344d00645'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_search_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('search_query', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('viewed_at', sa.DateTime(), nullable=True))
        batch_op.drop_column('timestamp')
        batch_op.drop_column('query')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_search_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('query', sa.VARCHAR(length=256), nullable=True))
        batch_op.add_column(sa.Column('timestamp', sa.DATETIME(), nullable=True))
        batch_op.drop_column('viewed_at')
        batch_op.drop_column('search_query')

    # ### end Alembic commands ###
