"""Re-align migration state

Revision ID: db34b1cc40db
Revises: 940ad01e65d3
Create Date: 2025-05-08 17:09:05.955609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db34b1cc40db'
down_revision = '940ad01e65d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('country', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=128), nullable=False))
        batch_op.alter_column('capital',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=128),
               existing_nullable=True)
        batch_op.alter_column('calling_code',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=10),
               existing_nullable=True)
        batch_op.alter_column('population',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('timezones',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.PickleType(),
               existing_nullable=True)
        batch_op.alter_column('currencies',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.PickleType(),
               existing_nullable=True)
        batch_op.alter_column('flag',
               existing_type=sa.VARCHAR(length=300),
               type_=sa.String(length=256),
               existing_nullable=True)
        batch_op.alter_column('languages',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.PickleType(),
               existing_nullable=True)
        batch_op.alter_column('latlng',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.PickleType(),
               existing_nullable=True)
        batch_op.create_unique_constraint("uq_country_name", ['name'])
        batch_op.drop_column('created_at')
        batch_op.drop_column('country_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('country', schema=None) as batch_op:
        batch_op.add_column(sa.Column('country_name', sa.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('latlng',
               existing_type=sa.PickleType(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('languages',
               existing_type=sa.PickleType(),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('flag',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=300),
               existing_nullable=True)
        batch_op.alter_column('currencies',
               existing_type=sa.PickleType(),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('timezones',
               existing_type=sa.PickleType(),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('population',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
        batch_op.alter_column('calling_code',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('capital',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.drop_column('name')

    # ### end Alembic commands ###
